// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snoyrmrjcirkjhomewrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub3lybXJqY2lya2pob21ld3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODAxNjAsImV4cCI6MjA1OTA1NjE2MH0.oZ0LOf7taIt4XymAcHKy9fZXdlNjDlKRAt1rqhKZXaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);